config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  get 'events/my_events'

  resources :events
  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]
  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @event = current_user.events.find_by(id: params[:id])
    redirect_to events_path, notice: 'Not authorized to edit this event' if @event.nil?
  end

  def my_events
    @events = Event.all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :description, :date, :location, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :title, class: "form-control", placeholder: "Event title" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_area :description, class: "form-control", placeholder: "Event description" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.date_select :date, class: "form-control", placeholder: "date" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :location, class: "form-control", placeholder: "Location" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :event_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  <br/>

  <div class="actions">
    <%= form.submit class:"btn -btn-secondary" %>
  </div>
  <br/>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event, class:"btn btn-secondary" %>
<%= link_to 'Back', events_path, class:"btn btn-dark" %>

app/views/events/index.html.erb
<!-- Add code to a helper -->
<% current_date = Date.today %>

<h4>Upcoming Events</h4>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Location</th>
      <th>Host</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <!-- Add code to a helper -->
      <% if current_date <= event.date  %>

        <tr>
          <td><%= event.title %></td>
          <td><%= event.description %></td>
          <td><%= event.date %></td>
          <td><%= event.location %></td>
          <td><%= event.user.username %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>

      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<h4>Past Events</h4>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Location</th>
      <th>Host</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <!-- Add code to a helper -->
      <% if current_date > event.date  %>

        <tr>
          <td><%= event.title %></td>
          <td><%= event.description %></td>
          <td><%= event.date %></td>
          <td><%= event.location %></td>
          <td><%= event.user.username %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>

      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Event', new_event_path, class: "btn btn-secondary" %>

app/views/events/my_events.html.erb
<h4>Created Events</h4>
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Location</th>
      <th>Host</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <!-- Add code to a helper -->
      <% if event.user == current_user  %>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.description %></td>
          <td><%= event.date %></td>
          <td><%= event.location %></td>
          <td><%= event.user.username %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br/>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class: "btn btn-dark" %>

app/views/events/show.html.erb
<div class="card">
  <div class="card-header">
    <h5 class="card-title"><%= @event.title %></h5>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @event.description %></p>
    <li class="list-group-item">
      <p>
        <strong>Date:</strong>
        <%= @event.date %>
      </p>
    </li>
    <li class="list-group-item">
      <p>
        <strong>Location:</strong>
        <%= @event.location %>
      </p>
    </li>
    <br/>
    <a href="#" class="btn btn-secondary">Attend Event</a>
  </div>
</div>


<br/>
<%= link_to 'Edit', edit_event_path(@event), class: "btn btn-secondary" %>
<%= link_to 'Back', events_path, class: "btn btn-dark" %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Private Events", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <!-- Add code to helper -->
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "New Event", new_event_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "My Events", events_my_events_path, class:"nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>

        <% end %>





      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <%= render "home/navbar" %>
    <div class="container">

      <br/>
       <!-- Add code to helper -->
      <% if notice %>  
        <%= render "layouts/alerts" %>
      <% end %>

      <br/>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>